### ISSUE TITLE
no-nominatim doesn't work

### ISSUE THREAD

**Issue by tooneamelter** [chesty/maps-docker-compose#4]
I know you no longer maintain this project but I'm wondering if you happen to know the resolution to this issue.  When I launch docker-compose.yml linked to the full yml it works great.  However, I'd like to not use nominatim and unfortunately, when I link docker-compose.yml to the no-nominatim it no longer works.  Init-db exits as expected but the <ip address>:8000 will not load the tiles and there are errors in the browser console that the tiles have a 502 error, not found.

I tested this in the past and just used nominatim as I just needed a working prototype for our project.  Now, I'm looking to go full planet but I really don't want to clog the server with nominatim as we won't use it for our purposes.  Any idea why the tiles wouldn't load and no map shown when using no-nominatim

**Comment by chesty** [comment]
I have some time today so I'll get it working again. I think it's to do with the nginx  proxy.  

btw, can you try using full and comment out nominatim? it will probably won't start because nominatim is referenced somewhere else, so you'll need to find the ref and comment those out as well.  but I'll still look at it today

and also I've never tested on full, updating the tiles might need to be tuned or tuned off.

**Comment by tooneamelter** [comment]
Awesome, thank you.

Also, is there a reason that the nginx/default.conf has the location /vroom proxying to http://vroom:3000/ and the nginx-no-nominatim/default.conf has that proxying to http://osrm-backend:3000/

Also, I'll try full with nominatim commented out right now

**Comment by chesty** [comment]
I  changed some things in  the full and didn't update no-nominatim. that's probably one reason why it doesn't work. there might be more.

I also edited my comment above about updating tiles

"and also I've never tested on full, updating the tiles might need to be tuned or tuned off."

**Comment by tooneamelter** [comment]
Awesome, it's running.  I'm just testing on Oceana but the server is 56 cores and 512GB RAM so it should be quick

**Comment by chesty** [comment]
sweet. can you update no-nominatim and send a pull request?

**Comment by tooneamelter** [comment]
Once I've tested I'll send a pull request.  I had to remove nominatim from full.yml and from nginx.  I'll keep you updated

**Comment by chesty** [comment]
thanks for the fix.
